# -*- coding: utf-8 -*-
"""AI-A4-Amulya-MT20004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3D-WV7idCC_2tVGD_AWLmONhgAQC77J
"""

!apt install swi-prolog
!pip install pyswip
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from pyswip import Prolog

def output(var):
    if var == "Teaching": 
      print('Since you are good in teaching domain you can express your knowledge')
      print('You are will be good in handling students and planning the classes')
      print('So we recommend you to take these skills forward and be a Teacher')
      print('You can be a Professor in some Government College')
      print('You can go for further Studies and become Lecturer in good college')

    if var == "Tech-Research": 
        print('Since you are good in practical as well as you are good at learning')
        print('You are a innovative and intutive person')
        print('So we recommend you to take these skills forward and be a Researcher')
        print('You can do research in Machine learning and Deep Learning')
        print('You can do research in some non technical fields also')

    if var == "DataAnalyst":
        print('Since you love mathematics and you like applying Technology')
        print('You are good at logical reasoning and moreover you are good in Machine Learning')
        print('We recommend you to persue Data Analysis as a career')
        print('You can be a Buisness Intelligence Analyst')
        print('You can be a Data Scientist')
        print('You can be a Data Engineer')
        print('You can be a Quantitative Analyst')
        print('You can be a Marketing Analyst')
        print('You can also go for research in this field.')

    if var == "BioInformatics_DataScientist":
        print('Since you have experience in Machine Learning and you like Biology')
        print('We suggest you to go for BioInformatics')
        print('You can be a Quantitative Biologist')
        print('You can be in field of Stochastic Simulation and Systems Biology ')
        print('You can be a Computational Neuroscientist')
        print('You can go for further studies in Deep Learning')
        print('You can also do a research in this field')

    if var == "SoftwareEngineer":
        print('Since you are good in coding, You are a logical and practical person and like coding')
        print('So we recommend you to take these skills forward and be a Software Engineer')
        print('You can be a Software Development Engineer')
        print('You can be a Software Developer')
        print('You can be a Algorithm expert')
        print('You can also go for Computer and Information Research Scientist')

    if var == "EthicalHacker":
        print('Since you are a logical person and practical person')
        print('You have experience in cyber field')
        print('We suggest that you can try your career in Cyber Security')
        print('You can be an Ethical Hacker')
        print('You can work in field of cryptography')
        print('You can be a cybersecurity architect')
        print('You can work in firld of security for big organisations')
        print('You can be a Cyber crime expert')
        print('You can also do a research in this field')

    if var == "Cloud_Virtualization_Expert":
        print('Since you are alogical and practical perosn and have experience in field of cloud and virtualization')
        print('You can persue career in Cloud Virtualization field')
        print('You can be a Cloud Server Manager')
        print('You can be a Cloud Analyst')
        print('You can be a Server Virtualization engineer')
        print('You can also go for research in thsi field')

    if var == "ImageAnalyst":
        print('Since you are good in training machines and you have done progect in fiels of Image Ananlysis')
        print('You can persue your career in Image Analysis')
        print('You can be a Computer Vision Expert')
        print('You can be a Image Analyst')
        print('You can do research in image processing algorithms')

    if var == "NetworkAdministrator":
        print('Since you are good at planning and coding')
        print('You have experience in field of networking')
        print('We recommend you to take these skills forward in the field of networking')
        print('You can be a Network engineer')
        print('You can be a Network Solution Architect')
        print('You can be a Network Programmer')
        print('You can be a Network Administrator')
        print('You can be a Network Analyst')
        print('You can also go for reseach in this field')

    if var == "BigDataSpecialist":
        print('Since you love mathematics and you like applying Technology')
        print('You are good at inductive reasoning and moreover you have practical experience in Big Data')
        print('We recommend BigDataSpecialist as a career')
        print('You can be a Data Architect')
        print('You can be a DataWarehouse Manager')
        print('You can be a Database Administrator')
        print('You can be a Buisness Intelligence Analyst')
        print('You can be a Data Scientist')
        print('You can also go for research in this field')

    if var == "DisasterRecoveryPlanner": 
        print('Since you are good at planning and you have a practical approach')
        print('You have forte of problem solving')
        print('We recommend you to take these skills forward and be in field of Disaster Recovery')
        print('You can be a Disaster Recovery Specialist')
        print('You can be a Disaster Recovery Planner')
        print('You can be a Disaster Risk Predictor')
        print('You can also explore more and go for research in this field')

    if var == "Designer":
        print('Since you are a creative and innovative person')
        print('You do not like coding much so You can think in direction of becoming a Designer')
        print('You can be a User experience designer')
        print('You can be a multimedia animator')
        print('You can be a Software UI designer')
        print('You can be a Product Designer')

    if var == "Non-Tech-Research":
        print('Since you are good in practical as well as you are good at learning')
        print('You are a innovative and intutive person')
        print('So we recommend you to take these skills forward and be a Researcher')
        print('You can do research in some non technical fields also')

    else:
        print("We recommend you to explore more about your interests and come back again.")

    print("==================================================================================================")

print('This my career advisory system that suggests you list of careers you can go for after MTECH-CSE')
print('Your marks do not decide your future but your aptitude interests and experience do matter')
print('Please answer the following, few questions->')

ps = PorterStemmer()

f = open("/content/travelfacts.txt", 'w')

inplist = []
inp1 = input("What is your general way of thinking - logical or intutive")
tok1 = word_tokenize(inp1)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "logic" in inplist:
  f.write("logic_intution(logic).\n")
elif  "intution" in inplist:
  f.write("logic_intution(intution).\n")

inplist = []
inp2 = input('What were your grades as a teaching Assistant- Satisfactory or unsatisfactory?')
tok1 = word_tokenize(inp2)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "satisfactori" in inplist:
  f.write("tagrades(s).\n")
elif  "unsatisfactori" in inplist:
  f.write("tagrades(xs).\n")

inplist = []
inp3 = input('In which of the subjects, you have an experience, choose any one?\n Cyber\n Cloud\n Network\n Image processing\n Bigdatadata\n none')

tok1 = word_tokenize(inp3)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "cyber" in inplist:
  f.write("experience(cyber).\n")
elif  "cloud" in inplist:
  f.write("experience(cloud).\n")
elif  "network" in inplist:
  f.write("experience(network).\n")
elif  "imag" in inplist:
  f.write("experience(image).\n")
elif  "bigdata" in inplist:
  f.write("experience(bigdata).\n")
else:
  f.write("experience(none).\n")

inplist = []
inp4 = input('Do you love Coding- Yes or No?')
tok1 = word_tokenize(inp4)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("coding(yes).\n")
else:
  f.write("coding(no).\n")

inplist = []
inp5 = input('Do you like Mathematics- Yes or No?')
tok1 = word_tokenize(inp5)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("maths(yes).\n")
else:
  f.write("maths(no).\n")

inplist = []
inp6 = input('Do you like Biology- Yes or No?')
tok1 = word_tokenize(inp6)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("biology(yes).\n")
else:
  f.write("biology(no).\n")

inplist = []
inp7 = input('Do you enjoy being theoritical or want to do things practically?')
tok1 = word_tokenize(inp7)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "theori" in inplist:
  f.write("theory_practical(theory).\n")
elif "practic" in inplist:
  f.write("theory_practical(practical).\n")

inplist = []
inp8 = input('Do you prefer to apply the existing technology or develop new technology?')
tok1 = word_tokenize(inp8)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "appli" in inplist:
  f.write("technology(apply_technology).\n")
elif "develop" in inplist:
  f.write("technology(develop_technology).\n")

inplist = []
inp9 = input('In which of the following fields, you are comfortable- \n machine\n application development\n problem solving\n none?')
tok1 = word_tokenize(inp9)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "machin" in inplist:
  f.write("forte(machine_learning).\n")
elif "applic" in inplist:
  f.write("forte(application_development).\n")
elif "solv" in inplist:
  f.write("forte(problem_solving).\n")
else:
  f.write("forte(none).\n")

inplist = []
inp10 = input('Do you want to learn more and more things life long?')
tok1 = word_tokenize(inp10)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("learner(yes).\n")
else:
  f.write("learner(no).\n")

inplist = []
inp11 = input('Are you a creative person liking arts and patterns?')
tok1 = word_tokenize(inp11)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("creative(yes).\n")
else:
  f.write("creative(no).\n")

inplist = []
inp12 = input('Do you like planning and organising things and situation?')
tok1 = word_tokenize(inp12)
for wod in tok1:
    stem1 = ps.stem(wod)
    inplist.append(stem1)
if "ye" in inplist:
  f.write("planning(yes).\n")
else:
  f.write("planning(no).\n")

f.close()

swipl = Prolog()
swipl.consult("/content/careerAdvisory.pl")
career_suggested = list(swipl.query("find_career(Career)"))
for i in range(len(career_suggested)):
    var = career_suggested[i]['Career'].decode('utf-8')
    output(var)
